-- Seed Projects
INSERT OR REPLACE INTO projects (id, title, category, description, tags, image_url, github_url, demo_url) VALUES
(1, 'Campus Hub Portal', 'web', 'Centralized web platform managing university schedules, event registrations, and real-time announcements.', '["TypeScript", "React", "Node.js", "PostgreSQL"]', 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=600&q=80', 'https://github.com', 'https://example.com'),
(2, 'Attendance & Quiz Tracker', 'mobile', 'Mobile application with instant QR-code validation for university attendance and real-time in-lecture quizzes.', '["Kotlin", "Android", "Firebase", "Material 3"]', 'https://images.unsplash.com/photo-1551650975-87deedd944c3?auto=format&fit=crop&w=600&q=80', 'https://github.com', NULL),
(3, 'Layered Cloud ERP Engine', 'web', 'Modular enterprise dashboard with microservices, clear separation of concerns, and clean RESTful endpoints.', '["Next.js", "Express", "MongoDB", "Tailwind"]', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80', 'https://github.com', NULL),
(4, 'Student Task & Budget App', 'mobile', 'Cross-platform mobile application combining academic milestone tracking with personal budgeting features.', '["Flutter", "Dart", "SQLite"]', 'https://images.unsplash.com/photo-1526470608268-f674ce90ebd4?auto=format&fit=crop&w=600&q=80', 'https://github.com', NULL);

-- Seed Team Members
INSERT OR REPLACE INTO team_members (id, name, role, description, image, avatar_icon, avatar_zoom, is_founder, github, linkedin, email, phone, education, key_skills, experience_highlights, cv_pdf_url) VALUES
('kasunara', 'BKB Kasunara', 'Co-Founder & Technical Architect', 'Guides overall system design, layered architecture, cloud backends, and full-stack software development.', 'assets/kasunaraksy.png', NULL, 'transform: scale(1.55); object-position: 50% 25%;', 1, 'https://github.com/BuwanjithKasunara', 'https://www.linkedin.com/in/buwanjith-kasunara-076045296/', 'ksytechlk@gmail.com', NULL, 'BSc (Hons) in Information Technology - General Sir John Kotelawala Defence University', '["System Architecture", "TypeScript", "Node.js", "Java", "Cloud Infrastructure", "API Design"]', '["Architected high-throughput layered software systems and asynchronous event drivers", "Directed core technical frameworks and engineering guidelines for KSY Tech"]', NULL),

('aththanayake', 'AMKD Aththanayake', 'Co-Founder & Head of Product', 'Leads technical roadmaps, mobile product strategies, and cross-platform mobile delivery.', 'assets/kavishkaksy.png', NULL, 'transform: scale(1.15); object-position: 50% 15%;', 1, 'https://github.com', 'https://www.linkedin.com/in/kavishka-dilshan-07044b243/', NULL, NULL, 'BSc (Hons) in Information Technology - General Sir John Kotelawala Defence University', '["Product Strategy", "Mobile Architecture", "Agile Roadmap Execution", "Cross-Platform Delivery"]', '["Formulates product architecture for enterprise mobile applications", "Leads cross-platform mobile sprint planning and release roadmaps"]', NULL),

('linali', 'Linali Wickrama', 'UI/UX Designer & Brand Communications', 'Crafts intuitive web & mobile user experiences in Figma and directs technical media, project demos, and brand communications.', 'assets/linaliksy.png', NULL, 'transform: scale(1.2); object-position: 50% 20%;', 0, 'https://github.com', 'https://linkedin.com', 'linalihasharal@gmail.com', '+94 704618886', 'BSc (Hons) in Information Technology - KDU (2024-Present) | Diploma in IT (SLTCA)', '["Figma", "Canva", "UI/UX Prototyping", "HTML/CSS", "Java", "MySQL", "Media Production"]', '["Compere and host at International Research Conference & GitSpark", "Uni Media Compering Head & Rotaract International Service Director", "High-fidelity responsive UI prototyping and client design system handoffs"]', 'Linali.pdf'),

('dinusha', 'Dinusha Kodithuwakku', 'Project Operations & Frontend Associate', 'Coordinates development sprints, project operations, and UI implementations across web and mobile client deliverables.', 'assets/senehasksy.png', NULL, 'transform: scale(1.2); object-position: 50% 18%;', 0, 'https://github.com', 'https://www.linkedin.com/in/senehas-kodithuwakku-20b2682b7', 'dinushasenehas2002@gmail.com', '+94 778414210', 'BSc (Hons) in Information Technology - KDU (2024-Present) | Rahula College Matara', '["Project Coordination", "Agile & Scrum", "HTML/CSS", "Java", "Photoshop", "Vibe Coding"]', '["Batch Representative (Intake 41 IT/IS) & IEEE Project Chair", "SEDS Southern Campus Coordinator & BCS Logistics Lead", "University Colours 2025 in Karate & Event Coordinator for SPL 2025"]', 'Dinusha.pdf'),

('kawindi', 'Kawindi Muhandiram', 'QA Engineer & Cloud Operations', 'Drives software quality assurance, system testing, bug reporting, and AWS/Docker deployment verification for client products.', 'assets/kawindiksy.png', 'fa-solid fa-vial-circle-check', NULL, 0, 'https://github.com', 'https://www.linkedin.com/in/KawindiMuhandiram', 'kawindimuhandiram@gmail.com', '+76 6785865', 'BSc (Hons) in Information Technology - KDU (3rd Year Undergraduate)', '["Software QA", "Functional & System Testing", "Bug Reporting", "AWS", "Docker", "Java", "Python"]', '["3 weeks testing practical experience on KDU University Hospital Management System", "2nd Place in Software Projects category at TechXhibit ''26", "PR Lead (TechXhibit ''26) & Secretary Team (IEEE XELERATE ''26)"]', 'Kawindi.pdf'),

('dehemi', 'Dehemi Wijesuriya', 'Finance Operations & Frontend Developer', 'Directs project budgeting, financial operations, and client coordination while contributing to React frontend implementations.', NULL, 'fa-solid fa-coins', NULL, 0, 'https://github.com', 'https://www.linkedin.com/in/dehemiwijesuriya', 'dehemiwijesuriya21@gmail.com', '+76 3120199', 'BSc (Hons) in Information Technology - KDU | Diploma in Psychology (IMBS)', '["Financial Management", "Budgeting", "React", "HTML/CSS", "UI/UX Design", "Git/GitHub"]', '["Treasurer for IEEE WIE Student Branch Affinity Group, KDU", "Finance Lead for IEEE WIE PIYAWARA CSR Project", "Student Coordinator for KDU Career Fair 2026 liaising with corporate exhibitors"]', 'Dehemi.pdf'),

('chamath', 'Chamath Rasanjana', 'Next.js Full-Stack Developer & Media Lead', 'Builds modern Next.js/Node.js web systems and generative AI integrations while directing visual media and video production.', NULL, 'fa-solid fa-code-branch', NULL, 0, 'https://github.com/Chamathmee', 'https://l1nk.dev/6w1q607', 'chamathrasanjana2003@gmail.com', NULL, 'BSc (Hons) in Information Technology - KDU (3rd Year) | CCNA Coursework', '["Next.js", "React / React Native", "Node.js", "Python", "Flask", "Gemini API", "MongoDB", "Videography"]', '["Developed Gemini API-integrated air quality and asthma advisory platform", "QA Team Member for KDU University Hospital Management System", "Built sports ground facility booking system and Next.js hardware management tools"]', 'Chamath.pdf'),

('pethmi', 'Pethmi Serasinghe', 'Full-Stack Web Developer & QA Specialist', 'Specializes in MERN stack web applications, AI scheduling algorithms, and enterprise quality assurance testing.', NULL, 'fa-solid fa-layer-group', NULL, 0, 'https://github.com/Pethmi001', 'https://h1.nu/1y99P', 'pethmiserasinghe@gmail.com', NULL, 'BSc (Hons) in Information Technology - KDU (3rd Year) | AI/ML Certification (SLIIT)', '["MERN Stack", "React.js", "Node.js", "MongoDB", "Express.js", "Python", "Software QA", "Figma"]', '["QA Team Member for KDU University Hospital Management System", "Developed MERN POS & Inventory System with rental/restoration tracking", "Engineered AI-based university examination timetable scheduling system"]', 'Pethmi.pdf'),

('adithya', 'A.K. Jayasundara', 'Cloud & AI Solutions Engineer', 'Architects serverless cloud platforms, real-time Firebase applications, and AI-driven workflows with React and Node.js.', 'assets/adithyaksy.png', NULL, 'transform: scale(1.2); object-position: 50% 15%;', 0, 'https://github.com', 'https://www.linkedin.com/in/adithya-jayasundara-397871394', 'adithyakesara12345@gmail.com', '0702203306', 'BSc (Hons) in Information Technology - KDU (Expected 2027)', '["React.js", "Firebase", "Node.js", "Prompt Engineering", "Python", "FastAPI", "C# / .NET", "gRPC"]', '["Engineered GuardEye smart security booking platform with live GPS tracking", "Developed SkyPulse AI weather platform using Gemini API natural language generation", "Experienced in serverless Firestore architectures and real-time push alerts"]', 'Adithya.pdf'),

('sarangi', 'Kavindya Rajapaksha', 'Associate Product Manager & UI/UX Designer', 'Directs project coordination, sprint documentation, and intuitive wireframes while ensuring quality control across client portals.', NULL, 'fa-solid fa-diagram-project', NULL, 0, 'https://github.com', 'https://www.linkedin.com/in/kavindya-rajapakshaksr03/', 'kavindyarajapaksha2003@gmail.com', '+94 71 538 5858', 'BSc (Hons) in Information Technology - KDU (3rd Year Undergraduate)', '["UI/UX Design", "Wireframing", "Project Management", "Business Analysis", "Software Testing", "Documentation"]', '["Project Manager & UI/UX Designer for Travora tour booking system", "Secretary of the IEEE Student Branch of KDU (2+ years leadership)", "Software QA tester for Online Banking System and Hospital Information Management System (HIMS)"]', 'Sarangi.pdf');